run:
  timeout: 3m
  go: "1.22"
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/quickowl/knify/apps/session-monitor
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
